# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_config.config.ipynb (unless otherwise specified).

__all__ = ['ope', 'sk', 'hostname', 'DEVICE', 'RESULT_DIR', 'DATA_DIR', 'PRETRAINED_DIR', 'TIF_DIR', 'EXTERNEL_DIR',
           'PI', 'INF', 'EPS', 'IMG_SIZE', 'NUM_CLASSES', 'ID', 'PREDICTED', 'TARGET', 'PARENTID', 'EXTERNAL',
           'ANTIBODY', 'ANTIBODY_CODE', 'LABEL_NAMES', 'LABEL_NAME_LIST', 'COLOR_INDEXS']

# Cell

import os
ope = os.path.exists
from pathlib import Path
import numpy as np
import torch
import socket
import warnings
warnings.filterwarnings('ignore')

from ..utils.common_util import *

# Cell

sk = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
hostname = socket.gethostname()
print('run on %s' % hostname)

# Cell

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Cell

RESULT_DIR     = Path("../../kgl_humanprotein_data/result")
DATA_DIR       = Path("../../kgl_humanprotein_data/protein")
PRETRAINED_DIR = Path("../../kgl_humanprotein_data/pretrained")
TIF_DIR        = Path("/data2/data/protein")
EXTERNEL_DIR   = Path("/data/data/protein")

# Cell

PI  = np.pi
INF = np.inf
EPS = 1e-12

# Cell

IMG_SIZE      = 512
NUM_CLASSES   = 28
ID            = 'Id'
PREDICTED     = 'Predicted'
TARGET        = 'Target'
PARENTID      = 'ParentId'
EXTERNAL      = 'External'
ANTIBODY      = 'antibody'
ANTIBODY_CODE = 'antibody_code'

# Cell
LABEL_NAMES = {
    0: 'Nucleoplasm',
    1: 'Nuclear membrane',
    2: 'Nucleoli',
    3: 'Nucleoli fibrillar center',
    4: 'Nuclear speckles',
    5: 'Nuclear bodies',
    6: 'Endoplasmic reticulum',
    7: 'Golgi apparatus',
    8: 'Intermediate filaments',
    9: 'Actin filaments',
    10: 'Microtubules',
    11: 'Mitotic spindle',
    12: 'Centrosome',
    13: 'Plasma membrane',
    14: 'Mitochondria',
    15: 'Aggresome',
    16: 'Cytosol',
    17: 'Vesicles and punctate cytosolic patterns',
    18: 'Negative'}

LABEL_NAME_LIST = [LABEL_NAMES[idx] for idx in range(len(LABEL_NAMES))]

# Cell

COLOR_INDEXS = {
    'red': 0,
    'green': 1,
    'blue': 2,
    'yellow': 0,
}