# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_utils.common_util.ipynb (unless otherwise specified).

__all__ = ['osp', 'ope', 'opj']

# Cell
import os
from pathlib import Path

osp = os.path
ope = os.path.exists
opj = os.path.join

Path.ls = lambda o: list(o.iterdir())