# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_utils.common_util.ipynb (unless otherwise specified).

__all__ = ['osp', 'ope', 'opj']

# Cell
import os

osp = os.path
ope = os.path.exists
opj = os.path.join