# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://qAp.github.io/kgl_humanprotein/"

git_url = "https://github.com/qAp/kgl_humanprotein/tree/master/"

def custom_doc_links(name): return None
